image: gitpod/workspace-full

tasks:
  - init: |
      nvm install 14 --lts
      yarn install
      yarn example:install
    command: |
      yarn example:start

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint
